dist: trusty
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
